# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunacheck < Formula
  desc "CLI to check web and TLS security properties"
  homepage "https://github.com/JoystiC/tunacheck"
  version "1.0.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JoystiC/tunacheck/releases/download/v1.0.2/tunacheck_darwin_amd64.tar.gz"
      sha256 "9eebef276af64cdfcdc1cc2b363e0ab4b46f133ebaf8f1cb32e350b877b4507e"

      def install
        bin.install "tunacheck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JoystiC/tunacheck/releases/download/v1.0.2/tunacheck_darwin_arm64.tar.gz"
      sha256 "77bda8784c759e3042c43b55755ceb7d77b43e176003117a5ff1a8138b7906aa"

      def install
        bin.install "tunacheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoystiC/tunacheck/releases/download/v1.0.2/tunacheck_linux_amd64.tar.gz"
      sha256 "2e6cc928e386d8d31e34ba45b677c6e12369222c7d7d5f3473b8a3840d1d375b"
      def install
        bin.install "tunacheck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoystiC/tunacheck/releases/download/v1.0.2/tunacheck_linux_arm64.tar.gz"
      sha256 "2ec96e0e5b5fd6aa6de27b758641d6d8d8a64319c134ca764412b6f4e773f68a"
      def install
        bin.install "tunacheck"
      end
    end
  end

  test do
    system "#{bin}/tunacheck", "version"
  end
end
