# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tunacheck < Formula
  desc "CLI to check web and TLS security properties"
  homepage "https://github.com/JoystiC/tunacheck"
  version "1.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JoystiC/tunacheck/releases/download/v1.1.1/tunacheck_darwin_amd64.tar.gz"
      sha256 "283fd92f485b77e7b01d737b7831c4897eec71d9b58ce16beea19ccb487e097a"

      def install
        bin.install "tunacheck"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JoystiC/tunacheck/releases/download/v1.1.1/tunacheck_darwin_arm64.tar.gz"
      sha256 "386aedc3be4400a6d5b6f4867c8f63c0aafa9f5dc4612a3f1ec787199a6f09b9"

      def install
        bin.install "tunacheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoystiC/tunacheck/releases/download/v1.1.1/tunacheck_linux_amd64.tar.gz"
      sha256 "f23ee42c4ac034068702588578a02f1db7ce55172f4fb4d5edc3955d588036e8"
      def install
        bin.install "tunacheck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JoystiC/tunacheck/releases/download/v1.1.1/tunacheck_linux_arm64.tar.gz"
      sha256 "451825fb4c72a6244789f6b370114404098d4302bdfbf0f71aa768e925039a28"
      def install
        bin.install "tunacheck"
      end
    end
  end

  test do
    system "#{bin}/tunacheck", "version"
  end
end
